export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const CHECK_LOGIN = 'SETISLOGIN';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTER_REQUESTED = 'REGISTER_REQUESTED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const GET_USER_PROFILE = 'GET_USER_PROFILE ';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const UPDATE_INFO_USER = 'UPDATE_INFO_USER';
export const UPDATE_AVATAR_USER = 'UPDATE_AVATAR_USER';
export const GET_LIST_TEAM = 'GET_LIST_TEAM';
export const GET_LIST_TEAM_SUCCESS = 'GET_LIST_TEAM_SUCCESS';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
